#!/bin/sh

OPTS=" -o BatchMode=yes -o StrictHostKeyChecking=no "
KEY="/images/amxa/amxa-tunnel.key"
CONFIG="/images/amxa/amxa-tunnel.config"

if test "$1" = "--template"; then
cat <<EOF >${CONFIG}
# adapt these values to your needs
# remote must be unique!
REMOTE="5556"
HOST="backup.amxa.ch"
USER="tunnel"
PORT="443"
EOF
exit 0
fi

if test -e ${CONFIG}; then
    source ${CONFIG}
else
    exit 1
fi


while true; do
    if test -e ${KEY}; then
	chmod 600 ${KEY}
	if ping -c 1  ${HOST} 2>/dev/null >/dev/null; then
            /usr/bin/autossh -N -p ${PORT} -i ${KEY} ${OPTS} -R ${REMOTE}:localhost:22 ${USER}@${HOST}
        fi
    fi
    sleep 300
done

exit
