#!/bin/sh

HOST=$(puavo-conf puavo.tunnel.ssh_host)
PORT=$(puavo-conf puavo.tunnel.ssh_port)
REMOTE=$(puavo-conf puavo.tunnel.remote_port)
KEY=$(puavo-conf puavo.tunnel.ssh_key)


if test -n "${KEY}";then 
#    echo ${KEY} >/root/key
#    chmod 600 /root/key
    echo /usr/bin/autossh -N -p${PORT} -i /root/key -o BatchMode=yes -o StrictHostKeyChecking=no -R ${REMOTE}:localhost:22 tunnel@${HOST}
else
    echo sleep 999999999999999
fi

exit
