#!/bin/sh

if test "$1" = "--template"; then
cat <<EOF >/images/amxa/amxa-tunnel.config
# adapt these values to your needs
REMOTE="5556"
HOST="backup.amxa.ch"
USER="tunnel"
PORT="443"
EOF

exit 0
fi


source /images/amxa/amxa-tunnel.config

OPTS=" -o BatchMode=yes -o StrictHostKeyChecking=no "
KEY="/images/amxa/key"

while true; do
    if test -e ${KEY}; then
	chmod 600 ${KEY}
	if ping -c 1  ${HOST} 2>/dev/null >/dev/null; then
            /usr/bin/autossh -N -p ${PORT} -i ${KEY} ${OPTS} -R ${REMOTE}:localhost:22 ${USER}@${HOST}
        fi
    fi
    sleep 300
done

exit
