Document: amxa-allinone-extra
Title: Debian amxa-allinone-extra Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-allinone-extra is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-allinone-extra/amxa-allinone-extra.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-allinone-extra/amxa-allinone-extra.ps.gz

Format: text
Files: /usr/share/doc/amxa-allinone-extra/amxa-allinone-extra.text.gz

Format: HTML
Index: /usr/share/doc/amxa-allinone-extra/html/index.html
Files: /usr/share/doc/amxa-allinone-extra/html/*.html
